### ISSUE TITLE
这个项目还在维护吗？

### ISSUE THREAD

**Issue by sunyuyangg555** [xuduo/stomp-app#1]
您好，这个项目还在维护吗？能否提供更多的信息，比如安装、配置、接口等？

**Comment by xuduo** [comment]
https://github.com/xuduo/misaka 可以看看这个

**Comment by xuduo** [comment]
不过目前是我们公司内部在用, 外网有些依赖你拿不到,很难用起来

**Comment by kd529** [comment]
无意之间发现这个项目，第一个默默关注了，给了赞，觉得这该项目会火，本为spring websocke stomp注解用，可惜此项目试用无果，后搁置，以为此项目沉寂，我也随之沉寂，当邮箱有消息而致，听闻很难复用，我的心又拔凉拔凉的
